version: "3.7"
services:
  dev-bot:
    build: .
    image: anomaly-discord-crashbot:dev
    container_name: dev-efp
    volumes:
    - ./src:/src # Overrides src added on image build
    environment: # Overrides config.json with .env
    - token=${token}
    - clientId=${clientId}
      #stdin_open: true # -i
      #tty: true # -t
    entrypoint: ["/bin/bash"] # Overrides CMD ["npm"], ["start"]
    restart: unless-stopped


