version: "3.7"
services:
  bot:
    image: asshall/anomaly-discord-crashbot
    container_name: prod-efp
    volumes:
    - ./src/secrets.json:/src/secrets.json # Copies secrets in
    restart: unless-stopped


