version: "3.7"
services:
  bot:
    image: asshall/anomaly-discord-crashbot:latest
    container_name: prod-efp
    volumes:
    - ./src/secrets.json:/src/secrets.json # Copies secrets in
    - ./logs:/logs
    restart: unless-stopped


